### ISSUE TITLE
Clean arrows from the body of players

### ISSUE THREAD

**Issue by WilliamPhoenix** [SmartPhoenix/Persistent-Kingdoms#215]
### Task Description
Clean arrows
### Specification/Explicit TODO
Make it so that the cloth removes blood and arrows, not just blood.

**Comment by Saptortacus** [comment]
Implemented.
Though, it is possible still that arrows will cause issues with "doors" (not tp doors), and thus disrupt the teleportation process. However, it is very unlikely since I have fired tons of arrows at several doors and it did not make any problems. In my understanding, the problem occured in the past because arrows were attached to the teleporter scene prop due to mappers positioning them too close to the player or too far away from the visual door.
