### ISSUE TITLE
White textures on linux/mac

### ISSUE THREAD

**Issue by WilliamTheBear** [SmartPhoenix/Persistent-Kingdoms#480]
### Task Description
White textures on linux/mac
### Specification/Explicit TODO
Textures are white on linux and mac.

**Comment by WilliamPhoenix** [comment]
Connected with custom shaders that are used in PW. I've tried replacing them with native shaders but then the scene props turn green.

"Due to some custom shaders used in PW, made with the Windows HLSL format before the Steam Mac / Linux versions were available: since they don't exist in the GLSL shader format necessary for your system, the meshes are rendered blank white. I have heard it should be possible to write/convert to GLSL shaders, but I don't have the time." - Written by Vornne.

So essentially the PW custom shaders would need to be converted from HLSL to GLSL format and that's a bit complicated. Will need some outsider help for that.

**Comment by WilliamPhoenix** [comment]
Conversation with Swyter about it:
https://pastebin.com/DY4xBu1b

**Comment by BridgeTrollPW** [comment]
On Linux with Steam this should no longer be an issue with Proton. Now steam can run Windows native Games on Linux. So warband has no more issues with the shaders there.

This also works if its not a steam game, e.g. warband directly from taleworlds. If you add the game you can also chose to execute with Proton.

Not sure about macOS tho
